name: "build: ubuntu20.04"

on: [push, pull_request]

jobs:
  build:
    name: build on ubuntu
    runs-on: ubuntu-20.04
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y qtbase5-dev libqt5svg5-dev libzmq3-dev libdw-dev

      - name: cmake generate makefile
        run: |
          cmake -B "${{ env.CMAKE_BUILD_DIR }}"
      - name: cmake build
        run: |
          cmake --build "${{ env.CMAKE_BUILD_DIR }}"
